### PR TITLE
SC-4675 Update calendar.js

### PR DESCRIPTION
**Pull request by alriese**
# Description

To be compliant with the future Content Security Policy, FullCalendar and the corresponding glue code have to be updated. 

## Links to Tickets or other pull requests

- https://ticketsystem.schul-cloud.org/browse/SC-4675

## Changes

- add gulp task to copy css files from depenendencies
- migrate FullCalendar from version 3 to version 4

## New Repos, NPM pakages or vendor scripts

- FullCalendar depenencies (in the new version spread across multiple packages)

- Gulp dependencies
  - [gulp-rename](https://www.npmjs.com/package/gulp-rename) (to rename the copied css files)
  - [merge-stream](https://www.npmjs.com/package/merge-stream) (to join multiple tasks)

## Screenshots of UI changes

Due to the obsolete Bootstrap version a visual error occurs. With the [Bootstrap update](https://github.com/schul-cloud/schulcloud-client/pull/1795) this issue will be fixed.

visual_bug

## Approval for review
- [X] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definition of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

### CODE REVIEW

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 52
- Added 11
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5676142&bid=18582763)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 52
- Added 11
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5676142&bid=18582763)

**Comment by alriese** [comment]
I would suggest, that we manage bootstrap (and poppler.js) over npm. Thus, we can update the libraries in the future more easily and keep them in sync. 

Since I had the same problem with bootstrap in my issue, and i was unaware of this issue, I started this approach on [a different branch](https://github.com/schul-cloud/schulcloud-client/pull/1916/commits/59d9eb1b7abd36d5b450892ecb12b1496176bf84).

I'd be happy if we could talk about that and sychronize our work.

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 52
- Added 12
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5676142&bid=18582763)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 52
- Added 12
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5676142&bid=18582763)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 52
- Added 3
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5676142&bid=18582763)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 52
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5676142&bid=18582763)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 52
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5676142&bid=18582763)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 50
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5676142&bid=18582763)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 52
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5676142&bid=18582763)

**Comment by janrenz** [comment]
@dominikbruechner Please take care of this PR or discard if we can move to vue in the neir future

**Comment by Metauriel** [comment]
@alriese some merge conflicts have to be solved.

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 61
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5676142&bid=18582763)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5676142&bid=18582763)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5676142&bid=18582763)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5676142&bid=18582763)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5676142&bid=18582763)

**Pull request merged**
