### PR TITLE
i18n SC-6529 Wrong language in team invitation

### PR DESCRIPTION
**Pull request by DevSchmidtchen**
Ticket: https://ticketsystem.schul-cloud.org/browse/SC-6529

**Affected Pages**
`/teams > open team detail view > click three dots next to team name > "Teammitglieder verwalten" > "Externe Teilnehmer einladen"`

**Before**
Before Screenshot

**After**
After Screenshot
After Screenshot Mobile View

### CODE REVIEW

**Review by janrenz — APPROVED** [review]

**Review by Parnswir — APPROVED** [review]

**Review by monaweitzenberg — CHANGES_REQUESTED** [review]
image
please change Button Text into: "Via E-Mail einladen" 
thx :)

**Review by monaweitzenberg — CHANGES_REQUESTED** [review]
Space between buttons would be helpful for the mobile-user, what do you think?

**Comment by DevSchmidtchen** [comment]
> Space between buttons would be helpful for the mobile-user, what do you think?

Generally a great idea but this would not only affect this screen. The spacing of the buttons is a global thing and therefore it would change the spacing of every button in mobile view. I think I shouldn't do this in this specific PR.

**Review by ABialoskorski — APPROVED** [review]

**Comment by ABialoskorski** [comment]
> Space between buttons would be helpful for the mobile-user, what do you think?

this is not part of this ticket, please create a ticket for that

**Review by monaweitzenberg — APPROVED** [review]

**Pull request merged**
