### PR TITLE
SC-5742 - replaced the settings icons

### PR DESCRIPTION
**Pull request by danielasofrone**
# Description
 Replaced the font awesome icons in the teams and courses pages

## Links to Tickets or other pull requests

- https://ticketsystem.schul-cloud.org/browse/SC-5742

## Changes

Replaced the font awesome icons to "fa fa-ellipsis-v" and updated the css to match the requirements

## Screenshots of UI changes
Before:
Old icon courses

After:
After

## Approval for review
- [x] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definition of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

### CODE REVIEW

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 71
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5960865&bid=19544311)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 30
- Added 99
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5960865&bid=19544311)

**Comment by Metauriel** [comment]
continued here: https://github.com/hpi-schul-cloud/schulcloud-client/pull/2079

**Comment by ABialoskorski** [comment]
please close this one, if this is continued in another PR

**Pull request closed without merging**
