### PR TITLE
update i18n mocha test

### PR DESCRIPTION
**Pull request by Tratori**
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6770

Refactored old test for de.json and added new tests for the en.json ensuring that both stay in sync during development

### CODE REVIEW

**Review by ABialoskorski — APPROVED** [review]
nice ;)

**Review by dominikbruechner — APPROVED** [review]
nice 👍

**Review by ABialoskorski — CHANGES_REQUESTED** [review]
small changes needed
image

**Comment by ABialoskorski** [comment]
> small changes needed
> image

fixed

**Review by ABialoskorski — APPROVED** [review]

**Pull request merged**
