### PR TITLE
Feature/sc 5838 prepare enable courseroute

### PR DESCRIPTION
**Pull request by Metauriel**
# Description

## Links to Tickets or other pull requests
- https://github.com/schul-cloud/schulcloud-server/pull/1583
- https://ticketsystem.schul-cloud.org/browse/SC-5837
- https://ticketsystem.schul-cloud.org/browse/SC-5838

## Approval for review
- [x] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definition of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

### CODE REVIEW

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5968118&bid=19567556)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5968118&bid=19567556)

**Comment by CeEv** [comment]
Screenshot_14
Maybe a local problem ..can you re-check if langue text id is matched.

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5968118&bid=19567556)

**Pull request merged**
