### PR TITLE
Feature/SC-2483/LTI 1.3 Support

### PR DESCRIPTION
**Pull request by dominikglandorf**
# Description
Due to Feathers security policy, encoding URL is necessary.

## Links to Tickets or other pull requests
Ticket: https://ticketsystem.schul-cloud.org/browse/SC-2483

Server PR: https://github.com/hpi-schul-cloud/schulcloud-server/pull/857
SHD PR: https://github.com/hpi-schul-cloud/superhero-dashboard/pull/95

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>
No changes here.

## Deployment
No changes.

## New Repos, NPM pakages or vendor scripts
No changes.

## Approval for review
- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definition of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

### CODE REVIEW

**Comment by malcm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 15
- Added 34
           

Complexity increasing per file
==============================
- controllers/tools.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/schulcloud-client/schulcloud-client/pullRequest?prid=4389877&bid=14884434)

**Comment by malcm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 15
- Added 34
           

Complexity increasing per file
==============================
- controllers/tools.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/schul-cloud/schulcloud-client/pullRequest?prid=4389877&bid=14884434)

**Comment by malcm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 34
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=4389877&bid=14884434)

**Comment by malcm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 41
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=4389877&bid=14884434)

**Comment by malcm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=4389877&bid=14884434)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- controllers/tools.js  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=4389877&bid=14884434)

**Comment by tofixx** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- controllers/tools.js  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/hpi-schul-cloud/schulcloud-client/pullRequest?prid=6045539&bid=19807422)

**Pull request closed without merging**
