### PR TITLE
SC-5707 - login page language depending on browser lang

### PR DESCRIPTION
**Pull request by ABialoskorski**
# Description
 
The login page should displayed in the language of the clients browser.

## Links to Tickets or other pull requests

- https://ticketsystem.schul-cloud.org/browse/SC-5707

## Changes

The language defined within the browser is given as a header of the request ("accept-language").
The client gets the matching language by parsing and filtering this header.
But this only happens on the login page.

## Approval for review
- [x] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definition of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

### CODE REVIEW

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- static/scripts/login.js  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5979434&bid=19606875)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- static/scripts/login.js  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5979434&bid=19606875)

**Comment by tofixx** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- static/scripts/login.js  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/hpi-schul-cloud/schulcloud-client/pullRequest?prid=6045517&bid=19807401)

**Review by mwolowyk-cap — APPROVED** [review]
very nice!

**Pull request merged**
