### PR TITLE
i18n SC-5336 Translation Administration Long Text

### PR DESCRIPTION
**Pull request by abralurrahman**
Base links to copy
- https://ticketsystem.schul-cloud.org/browse/SC-5336

### CODE REVIEW

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 12
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5772596&bid=18894274)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 12
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5772596&bid=18894274)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 12
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5772596&bid=18894274)

**Comment by DevSchmidtchen** [comment]
It looks like you reverted some changes from develop-branch, so you've changed 44 files and removed already existing translations. Maybe you can fix this.

**Comment by abralurrahman** [comment]
> It looks like you reverted some changes from develop-branch, so you've changed 44 files and removed already existing translations. Maybe you can fix this.

**Comment by abralurrahman** [comment]
> It looks like you reverted some changes from develop-branch, so you've changed 44 files and removed already existing translations. Maybe you can fix this.

It happened because of merge! i didn't revert actually.

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 12
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5772596&bid=18894274)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 12
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5772596&bid=18894274)

**Pull request closed without merging**
