### PR TITLE
Feature/sc 6063/add evaluation delet function

### PR DESCRIPTION
**Pull request by CeEv**
Please see the single commits for non linter changes.

# Description

## Links to Tickets or other pull requests
- https://ticketsystem.schul-cloud.org/browse/SC-6036
- related to https://ticketsystem.schul-cloud.org/browse/SC-6098

## Approval for review
- [x] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definition of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

### CODE REVIEW

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 64
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=6001385&bid=19675871)

**Comment by CeEv** [comment]
> 
> 
> there ar e alot of apckage chages, have you reviewed them?

I think so. I run npm install to get the new CK-Editor. Maybe i have a older npm version as @alriese (he update the editor to Version 5).
@alriese can you please look into it. I want to merge it with package-lock, if you have not veto again it.

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 74
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=6001385&bid=19675871)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 74
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=6001385&bid=19675871)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 74
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=6001385&bid=19675871)

**Pull request merged**
