### PR TITLE
SC-5915: a11y homework details

### PR DESCRIPTION
**Pull request by haniapalac**
# Description

The dropdown issues will be fixed by these tickets: SC-5952 and SC-5858
the issue with weird focus behavior for upload section should be handled by this ticket: SC-5957
issues with the ckeditor should also be handled separately.

1. Labels are associated to the input fields (except input fields created with external libraries -> these should be handled in a different ticket)
2. Contrast issues are fixed.
3. file upload is accessible with a keyboard

## Links to Tickets or other pull requests

https://ticketsystem.schul-cloud.org/browse/SC-5915

## Changes

image

## Approval for review
- [x] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definition of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

### CODE REVIEW

**Review by luizzaly — COMMENTED** [review]
Bildschirmfoto 2020-08-24 um 12 43 00

Please remove the <p> here :)

**Comment by haniapalac** [comment]
> Bildschirmfoto 2020-08-24 um 12 43 00
> 
> Please remove the p tag here :)

AAA! Well spotted :D

**Comment by haniapalac** [comment]
> > Bildschirmfoto 2020-08-24 um 12 43 00
> > Please remove the p tag here :)
> 
> AAA! Well spotted :D

Could you please check again?

**Comment by qnowak** [comment]
> > > Bildschirmfoto 2020-08-24 um 12 43 00
> > > Please remove the p tag here :)
> > 
> > 
> > AAA! Well spotted :D
> 
> Could you please check again?

image

**Comment by luizzaly** [comment]
> > > > Bildschirmfoto 2020-08-24 um 12 43 00
> > > > Please remove the p tag here :)
> > > 
> > > 
> > > AAA! Well spotted :D
> > 
> > 
> > Could you please check again?
> 
> image

For me it is still there but somehow I can not find the issue here..

**Review by qnowak — APPROVED** [review]

**Review by luizzaly — APPROVED** [review]

**Pull request merged**
