### PR TITLE
[#SC-4064] Change download file names (3+4/4)

### PR DESCRIPTION
**Pull request by lwassermann**
# Description

Allow bulk upload of bulk-downloaded files. The idea is that a teacher can download all handed in files. Edit them locally, e.g. by annotating them, and then re-upload them all, grading a whole class at once.

Review-Tip:
- Enable `Ignore Whitespace changes` in the github diff options. The static file that was refactored a bit had bad whitespace (space) before. And there were enough changes to warrant fixing it now. Enabling this halves the diff.
- Because the file with fixed whitespace counts as changed for the lint-daemon, it complains about missing adjustments. I've started with those, but I think they just confuse the diff, so I stopped.

## Links to Tickets or other pull requests
Part 3 and 4 of [#SC-4064](https://ticketsystem.schul-cloud.org/browse/SC-4064)
Based on https://github.com/schul-cloud/schulcloud-client/pull/1780
Requires https://github.com/schul-cloud/schulcloud-server/pull/1242 ⚠️ 

## Changes

- Rename files downloaded with bulk-download
- Add file input on the homework submission screen (only visible to teachers)
- Extract module for bulk up and download
- Extract module for submission file uploading
- Add code for uploading without dropzone

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

No changes

## Deployment

No changes

## Screenshots of UI changes

Image with the new bulk-upload input element
Screenshot 2020-04-30 at 18 24 50

Feedback in case not all selected files could be automatically assigned (because the file names do not match our generated ones).
Screenshot 2020-04-30 at 18 31 36

Screenshot of the bulk-download file renaming. This is slightly outdated, because it does not yet include the upload-input
Screenshot 2020-04-29 at 14 25 06

## Approval for review
- [x] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definition of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

Marked as draft because the PRs it's based on are not yet merged. And there should be merged conflicts.

### CODE REVIEW

**Comment by malcm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 27
- Added 8
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5450657&bid=17871249)

**Comment by malcm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 31
- Added 6
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5450657&bid=17871249)

**Comment by malcm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 31
- Added 6
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5450657&bid=17871249)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 28
- Added 1
           

Complexity increasing per file
==============================
- static/scripts/homework/bulk-upload.js  2
- static/scripts/homework/api-requests.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5450657&bid=17871249)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 28
- Added 1
           

Complexity increasing per file
==============================
- static/scripts/homework/bulk-upload.js  2
- static/scripts/homework/api-requests.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5450657&bid=17871249)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 28
- Added 1
           

Complexity increasing per file
==============================
- static/scripts/homework/api-requests.js  1
- static/scripts/homework/bulk-upload.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5450657&bid=17871249)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 28
- Added 1
           

Complexity increasing per file
==============================
- static/scripts/homework/api-requests.js  1
- static/scripts/homework/bulk-upload.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5450657&bid=17871249)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 28
- Added 2
           

Complexity increasing per file
==============================
- static/scripts/homework/api-requests.js  1
- static/scripts/homework/bulk-upload.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5450657&bid=17871249)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 28
- Added 2
           

Complexity increasing per file
==============================
- static/scripts/homework/bulk-upload.js  2
- static/scripts/homework/api-requests.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5450657&bid=17871249)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 28
- Added 2
           

Complexity increasing per file
==============================
- static/scripts/homework/bulk-upload.js  2
- static/scripts/homework/api-requests.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5450657&bid=17871249)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 28
- Added 2
           

Complexity increasing per file
==============================
- static/scripts/homework/bulk-upload.js  2
- static/scripts/homework/api-requests.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5450657&bid=17871249)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 28
- Added 2
           

Complexity increasing per file
==============================
- static/scripts/homework/api-requests.js  1
- static/scripts/homework/bulk-upload.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5450657&bid=17871249)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 28
- Added 1
           

Complexity increasing per file
==============================
- static/scripts/homework/api-requests.js  1
- static/scripts/homework/bulk-upload.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5450657&bid=17871249)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 28
- Added 1
           

Complexity increasing per file
==============================
- static/scripts/homework/bulk-upload.js  2
- static/scripts/homework/api-requests.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5450657&bid=17871249)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 29
- Added 1
           

Complexity increasing per file
==============================
- static/scripts/homework/bulk-upload.js  2
- static/scripts/homework/api-requests.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5450657&bid=17871249)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 29
           

Complexity increasing per file
==============================
- static/scripts/homework/api-requests.js  1
- static/scripts/homework/bulk-upload.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5450657&bid=17871249)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 29
           

Complexity increasing per file
==============================
- static/scripts/homework/api-requests.js  1
- static/scripts/homework/bulk-upload.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5450657&bid=17871249)

**Pull request merged**
